# Generated by Django 3.2.4 on 2022-05-15 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=400)),
                ('memory', models.CharField(max_length=50)),
                ('technical_process', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 5, 16, 0, 16, 35, 105390))),
            ],
        ),
        migrations.DeleteModel(
            name='VideoCart',
        ),
    ]
