# Generated by Django 3.2.4 on 2022-05-17 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220517_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 5, 17, 20, 51, 13, 434845)),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 5, 17, 20, 51, 13, 434845)),
        ),
    ]
